"""add client_id to jobs

Revision ID: e944e0641b97
Revises: 3441b8fb192c
Create Date: 2025-06-09 12:18:39.873695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e944e0641b97'
down_revision: Union[str, None] = '3441b8fb192c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "jobs",
        sa.Column("client_id", sa.String(), nullable=False, server_default="")
    )
    op.create_index("ix_jobs_client_id", "jobs", ["client_id"], unique=False)
    # then drop the default
    op.alter_column("jobs", "client_id", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'jobs',
        sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('schedule', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    # ### end Alembic commands ###
